apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress  # wordpressというラベルが付与されたpodを参照する
    tier: frontend
  type: LoadBalancer